# Generated by Django 4.2.3 on 2023-07-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='dia_pagamento',
            field=models.DateField(),
        ),
    ]
