# Generated by Django 4.2.3 on 2023-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_contapagar_dia_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='dia_pagamento',
            field=models.IntegerField(),
        ),
    ]
